spring:
  config:
    activate:
      on-profile: example

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

master:
  password: ${MASTER_PASSWORD:}
